# https://cloud.google.com/appengine/docs/the-appengine-environments#comparing_high-level_features
# https://cloud.google.com/appengine/docs/standard

runtime: java17
instance_class: F2

env_variables:
  pusher.appId: "2144608"
  pusher.key: "5ecf3b7d78089be3782f"
  pusher.secret: "2b349d34fd9136e01138"
  pusher.cluster: "eu"