# https://cloud.google.com/appengine/docs/the-appengine-environments#comparing_high-level_features
# https://cloud.google.com/appengine/docs/standard

runtime: java17
instance_class: F2

env_variables:
  PUSHER_APP_ID: 2144608
  PUSHER_KEY: 5ecf3b7d78089be3782f
  PUSHER_SECRET: 2b349d34fd9136e01138
  PUSHER_CLUSTER: eu